import Head from "next/head";
// import ErrorSvg from "../error.svg";4
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.background}></div>
        <section className={styles.loginPage}>
          <div className={styles.logoHeader}>
            <Image
              className={styles.logo}
              src="/amazon.svg"
              alt="logo"
              width="99"
              height="32"
            />
          </div>
          <h1 className={styles.loginText}>login</h1>
          <div className={styles.tree}></div>
          <form className={styles.form}>
            <div className={styles.form__group}>
              <input
                type="email"
                id="email"
                className={styles.form__field}
                placeholder="Your Email"
              />
              <label htmlFor="email" className={styles.form__label}>
                Email
              </label>
              <div className={styles.errorMessage}>
                <Image src="/error.svg" height="16" width="16" alt="Err" />
                <p>This email field is required</p>
              </div>
            </div>

            <div
              className={`${styles.form__group} ${styles.password_form_group} `}
            >
              <input
                type="password"
                id="password"
                className={styles.form__field}
                placeholder="Your password"
              />
              <label htmlFor="password" className={styles.form__label}>
                Password
              </label>
            </div>

            <button className={styles.signInButton}> Sign In</button>
          </form>
          <div className={styles.secondaryActions}>
            <button className={styles.forgotPasswordButton}>
              Forgot Password?
            </button>
            <button className={styles.signUpButton}> New User ? Sign Up</button>
          </div>

          <p className={styles.orText}> or </p>

          <button className={`${styles.authButton} ${styles.googleAuthButton}`}>
            <Image
              src="/google.png"
              alt="google"
              width="36"
              height="36"
              className={styles.authButtonLogo}
            />
            continue with google
          </button>

          <button
            className={`${styles.authButton} ${styles.facebookAuthButton}`}
          >
            <Image
              src="/facebook.png"
              alt="facebook"
              width="36"
              height="36"
              className={styles.authButtonLogo}
            />
            continue with facebook
          </button>
        </section>
      </main>
    </div>
  );
}
