import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="absolute inset-0 mx-auto w-full bg-white">
        <div className="absolute inset-0 h-[263px] w-full border border-solid border-gray bg-trees bg-cover bg-no-repeat"></div>
        <section className="absolute top-[81px] left-1/2 w-11/12 translate-x-[-50%] rounded-md bg-white xs:w-10/12 md:w-[577px]">
          <div className="flex h-[58px] w-full items-center justify-center rounded-t-md rounded-r-md bg-white shadow-[0px_3px_7px_#00000029]">
            <Image src="/amazon.svg" alt="logo" width="99" height="32" />
          </div>
          <div className="px-3 xs:px-10 sm:px-16">
            <h1 className="mt-4 text-center text-[29px] capitalize leading-[35px] tracking-normal text-primary">
              login
            </h1>
            <div className="mx-auto mt-6 h-32 w-full bg-tree bg-center bg-no-repeat"></div>
            <form className="mx-auto mt-6 ">
              <div className="h-[46px] w-full">
                <input
                  type="email"
                  id="email"
                  className="w-full border-b-2 border-lightgray bg-transparent py-[7px] px-1 transition-colors duration-200 placeholder:text-primary focus:border-primary focus:outline-none"
                  placeholder="Email"
                />
                <div className="mt-[5px] flex items-center gap-1 text-xs text-secondary md:text-[14px]">
                  <div className="relative h-3 w-3 md:h-4 md:w-4">
                    <Image src="/error.svg" fill alt="Err" />
                  </div>
                  <p>This email field is required</p>
                </div>
              </div>

              <div className="mt-5 h-[25px] w-full">
                <input
                  type="password"
                  id="password"
                  className="w-full  border-b-2 border-lightgray bg-transparent py-[7px] px-1 transition-colors duration-200 placeholder:text-primary focus:border-primary focus:outline-none"
                  placeholder="Password"
                />
              </div>

              <button className="mt-7 h-10 w-full rounded-full border-none bg-primary leading-6 text-white md:h-[49px] md:text-[19px] ">
                Sign In
              </button>
            </form>
            <div className="mx-auto mt-4 flex items-center justify-between">
              <button className="h-[15px] bg-none text-left text-[14px] leading-[18px]">
                Forgot Password?
              </button>
              <button className="h-[15px] bg-none text-left text-[14px] leading-[18px] text-secondary">
                New User ? Sign Up
              </button>
            </div>

            <p className="mt-4 text-center leading-[18px]"> or </p>

            <div className="mx-auto mt-6 w-full">
              <button className="relative h-[46px] w-full border-none bg-blue text-center text-sm uppercase text-white">
                <div className="absolute inset-x-1 top-[9px] h-7 w-7 md:inset-1 md:h-9 md:w-9">
                  <Image
                    src="/google.png"
                    alt="google"
                    fill
                    className="object-cover"
                  />
                </div>
                continue with google
              </button>

              <button className=" relative mt-4 h-[46px] w-full border-none bg-blue text-center text-sm uppercase text-white">
                <div className="absolute inset-x-1 top-[9px] h-7 w-7 md:inset-1 md:h-9 md:w-9">
                  <Image
                    src="/facebook.png"
                    alt="facebook"
                    fill
                    className="object-cover"
                  />
                </div>
                continue with facebook
              </button>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
