import Head from "next/head";
import Image from "next/image";
import LoginForm from "../components/login-form";
import OAuthButtons from "../components/oauth-buttons";

export default function Home() {
  return (
    <div className="w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="absolute inset-0 mx-auto w-full bg-white">
        <div className="absolute inset-0 h-[263px] w-full border border-solid border-gray bg-trees bg-cover bg-no-repeat"></div>
        <section className="absolute top-[81px] left-1/2 w-11/12 translate-x-[-50%] rounded-md bg-white xs:w-10/12 md:w-[577px]">
          <div className="flex h-[58px] w-full items-center justify-center rounded-t-md rounded-r-md bg-white shadow-[0px_3px_7px_#00000029]">
            <Image src="/amazon.svg" alt="logo" width="99" height="32" />
          </div>
          <div className="px-3 xs:px-10 sm:px-16">
            <h1 className="mt-4 text-center text-[29px] capitalize leading-[35px] tracking-normal text-primary">
              login
            </h1>
            <div className="mx-auto mt-6 h-32 w-full bg-tree bg-center bg-no-repeat"></div>

            <LoginForm />

            <p className="mt-4 text-center leading-[18px]"> or </p>

            <OAuthButtons />
          </div>
        </section>
      </main>
    </div>
  );
}
